# Bumps NPM prerelease version on dev branch

trigger:
  branches:
    include:
    - dev
  paths:
    include:
    - azure/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  clean: true
  persistCredentials: true
  fetchDepth: 1

- task: npmAuthenticate@0
  displayName: 'npm Authenticate core/.npmrc'
  inputs:
    workingFile: core/.npmrc

- bash: |
    SOURCE_BRANCH_NAME=${SOURCE_BRANCH/refs\/head\/}
    git config --local user.email "Azure Pipelines"
    git config --local user.name "azuredevops@microsoft.com"
    NPM_VERSION=`npm version prerelease`
    git add package.json
    git commit -m "Auto bumping NPM prerelease version ***NO_CI***"
    git tag ${NPM_VERSION}
    git push origin HEAD:${SOURCE_BRANCH_NAME} --tags
  name: BumpNpmVersion
  displayName: Bump NPM Prerelease Version
  workingDirectory: azure/
  env:
    NPM_TOKEN: $(NPM_TOKEN)
    SOURCE_BRANCH: $(Build.SourceBranch)
