# Bumps NPM prerelease version on dev branch

trigger:
  branches:
    include:
    - wabrez/commit-prerelease
  paths:
    include:
    - core/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: 10.x

- checkout: self
  clean: true
  persistCredentials: true
  fetchDepth: 1

- task: npmAuthenticate@0
  displayName: 'npm Authenticate core/.npmrc'
  inputs:
    workingFile: core/.npmrc

- bash: |
    SOURCE_BRANCH_NAME=${SOURCE_BRANCH/refs\/head\/}
    git config --local user.email "Azure Pipelines"
    git config --local user.name "azuredevops@microsoft.com"
    NPM_VERSION=`npm version prerelease`
    
    git add package.json
    git add package-lock.json
    
    # Since there isn't a package.json at the root of repo 
    # we need to manually commit and tag
    git commit -m "Bumping NPM prerelease to version ${NPM_VERSION} ***NO_CI***"
    git tag ${NPM_VERSION}
    git push origin ${SOURCE_BRANCH_NAME} --tags
  name: BumpNpmVersion
  displayName: Bump NPM Prerelease Version
  workingDirectory: core/
  env:
    NPM_TOKEN: $(NPM_TOKEN)
    SOURCE_BRANCH: $(Build.SourceBranch)
