# Bumps NPM version on specified branch base on release type

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: 10.x

- checkout: self
  clean: true
  persistCredentials: true
  fetchDepth: 1

- task: npmAuthenticate@0
  displayName: 'npm Authenticate azure/.npmrc'
  inputs:
    workingFile: azure/.npmrc

- task: Bash@3
  name: BumpNpmVersion
  displayName: Bump NPM Prerelease Version
  inputs:
    targetType: filePath
    filePath: ./scripts/version.sh
    arguments: '@multicloud/sls-azure $(NPM_RELEASE_TYPE)'
    workingDirectory: azure
  env:
    NPM_TOKEN: $(NPM_TOKEN)
    SOURCE_BRANCH: $(Build.SourceBranch)
